name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V28

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: gaelreyrol

      - name: Run Flake check
        run: nix flake check

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V28

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: gaelreyrol

      - name: Build package
        run: nix build

      - name: Deploy build
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result